---

- name: Nginx Server
  hosts: webserver
  remote_user: root
  roles:
    - role: geerlingguy.nginx
    - role: scathatheworm.net-snmp
      snmpd_community_acl:
      - type: rocommunity
        community_name: public
    - role: "roles/centreon-config"
      centreon_admin_password: "p4ssw0rd"
      centreon_webapi_host: "http://192.168.150.10"
      centreon_webapi_port: "80"
      configuration:
          cg:
          - {
            'name': 'testers',
            'alias': 'Testers contacts',
            'state': 'enabled' # enabled, disabled, absent
            }
          contact:
          - {
            'name': 'Test contact One',
            'alias': 'test01',
            'email': 'test01@test.centreon.com',
            'password': 'easypass',
            'admin': '0',
            'gui': '1',
            'language': 'en_US',
            'auth_type': 'local',
            'state': 'enabled' # enabled, disabled, absent
            }
          host:
            - {
              'name': 'nginx_webserver',
              'alias': 'Web Server tests',
              'address': '192.168.150.100',
              'template': 'generic-active-host-custom|OS-Linux-SNMP-custom',
              'instance': 'central',
              'hostgroup': '',
              'snmp_community': ' public',
              'snmp_version': '1',
              'notes': ' this is a example of notes',
              'state': 'enabled' # enabled, disabled, absent
            }
          service:
            - {
              'description': 'port_80',
              'host name': 'nginx_webserver',
              'template': 'generic-active-service',
              'check_command': 'check_centreon_dummy',
              'notes': 'other example of notes',
              'state': 'enabled' # enabled, disabled, absent
              }
            - {
              'description': 'port_443',
              'host name': 'nginx_webserver',
              'template': 'generic-active-service',
              'check_command': 'check_centreon_dummy',
              'notes': 'other example of notes',
              'state': 'enabled' # enabled, disabled, absent
              }
